import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"

import Background from "~/app/_components/layout/Background"
import ThemeProvider from "~/app/utils/providers/ThemeProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Background>{children}</Background>
        </ThemeProvider>
      </body>
    </html>
  )
}
