import "@cryptohub/ui/globals.css"

import type { Metadata } from "next"
import localFont from "next/font/local"

const blink = localFont({
  src: [
    {
      path: "../public/fonts/blinkmacsystemfont-medium.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/blinkmacsystemfont-semibold.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/blinkmacsystemfont-bold.ttf",
      weight: "500",
      style: "bold",
    },
  ],
  display: "swap",
  variable: "--font-BlinkMacSystemFont",
})


export const metadata: Metadata = {
  title: "CyrptoHub | Market",
  description: "Generated by create turbo",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en" className="dark">
      <body className={blink.className}>{children}</body>
    </html>
  )
}
